{% set name = "tensorflow-probability" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/probability/archive/v{{ version }}.tar.gz
  sha256: 755d38db20a08d1b7d344ca00177e771525e473a6ab0922467b354da5df0a31e
  patches:
    - 0001-always-build-release.patch

build:
  noarch: python
  number: 0
  # The upstream directions say to use bazel, but this is
  # all bazel ends up doing. Since our bazel package can have
  # glibc version issues on CI, just do things this way.
  script: 
    - rm -f BUILD
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    # NOTE: tf is currently pulled in from defaults,
    #       so we have flexible channel priority set
    #       in conda-forge.yml
    - tensorflow-base >=2.3,<3
    - numpy >=1.13.3
    - six >=1.10.0
    - decorator
    - cloudpickle >=1.3
    - gast >=0.3.2
    - dm-tree

test:
  imports:
    - tensorflow_probability

about:
  home: https://www.tensorflow.org/probability/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow'

  description: |
    TensorFlow Probability is a library for probabilistic reasoning 
    and statistical analysis in TensorFlow. As part of the TensorFlow
    ecosystem, TensorFlow Probability provides integration of
    probabilistic methods with deep networks, gradient-based inference
    via automatic differentiation, and scalability to large datasets
    and models via hardware acceleration (e.g., GPUs) and distributed
    computation.
  doc_url: https://www.tensorflow.org/probability/overview
  dev_url: https://github.com/tensorflow/probability

extra:
  recipe-maintainers:
    - sodre
    - adbeda
    - oblute
    - rluria14
    - mayou36
